added shadow password option to configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -856,6 +856,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
+  --disable-shadow        Disable support for shadow passwords
 
 Some influential environment variables:
   CC          C compiler command
@@ -4399,6 +4400,192 @@ done
 
 
 
+
+
+# Check whether --enable-shadow or --disable-shadow was given.
+if test "${enable_shadow+set}" = set; then
+  enableval="$enable_shadow"
+
+else
+  enable_shadow=yes
+fi;
+
+if test "A$enable_shadow" = "Ayes"; then
+  if test "${ac_cv_header_shadow_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for shadow.h" >&5
+echo $ECHO_N "checking for shadow.h... $ECHO_C" >&6
+if test "${ac_cv_header_shadow_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_shadow_h" >&5
+echo "${ECHO_T}$ac_cv_header_shadow_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking shadow.h usability" >&5
+echo $ECHO_N "checking shadow.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <shadow.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking shadow.h presence" >&5
+echo $ECHO_N "checking shadow.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <shadow.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: shadow.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: shadow.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: shadow.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: shadow.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: shadow.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: shadow.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: shadow.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: shadow.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: shadow.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: shadow.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: shadow.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: shadow.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: shadow.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: shadow.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: shadow.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: shadow.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for shadow.h" >&5
+echo $ECHO_N "checking for shadow.h... $ECHO_C" >&6
+if test "${ac_cv_header_shadow_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_shadow_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_shadow_h" >&5
+echo "${ECHO_T}$ac_cv_header_shadow_h" >&6
+
+fi
+if test $ac_cv_header_shadow_h = yes; then
+  :
+else
+  shadow_available=no
+fi
+
+
+fi
+
+echo "$as_me:$LINENO: checking for shadow passwords support" >&5
+echo $ECHO_N "checking for shadow passwords support... $ECHO_C" >&6
+
+if test "A$enable_shadow" = "Ayes"; then
+  if test "A$shadow_available" = "Ano"; then
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+ 	echo "***"
+	echo "*** Warning: shadow passwords support disabled"
+	echo "***"
+	enable_shadow="no"
+  else
+ 	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SHADOW 1
+_ACEOF
+
+  fi
+else
+ 	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+	echo "***"
+	echo "*** Shadow passwords support disabled on command line"
+	echo "*** Use --enable-shadow to enable it"
+	echo "***"
+	enable_shadow="no"
+fi
 
                                                             ac_config_files="$ac_config_files Makefile src/Makefile doc/Makefile orig/Makefile themes/Makefile themes/default/Makefile"
 cat >confcache <<\_ACEOF
